# Server host
server.address=0.0.0.0
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=walkername

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/messenger_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# CORS Allowed Origins
cors.allowed.origins=https://localhost:5173,https://192.168.0.14:5173

# PostgreSQL
spring.jpa.properties.hibernate.show_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
