# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/messenger_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# CORS Allowed Origins
cors.allowed.origins=http://localhost:5173

# PostgreSQL
spring.jpa.properties.hibernate.show_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
