spring.datasource.url=jdbc:postgresql://postgresql:5432/messenger_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# CORS Allowed Origins
cors.allowed.origins=http://frontend:3000
