spring.profiles.active=dev

spring.application.name=backend

# PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.contexts=dev
spring.liquibase.default-schema=public

# Secret key
auth.jwt.access=messenger
auth.jwt.refresh=messenger
